# -*- coding: utf-8 -*-
"""Parcial Minería

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lF7WaRD7SKAJFx5OdyCEDzFlwSSQBNCo

Diego Fernando Vargas Poveda
Parcial Minería de datos

Dada una encuesta realizada a dos colegios en las cuáles se tiene información socioeconómica y académica de los estudiantes que se encuentra en student-mat.csv junto con su respectivo 
diccionario de datos, responda las siguientes preguntas dentro del Word.¿Existen valores vacíos o 
nulos para alguna de las variables del dataset?
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import matplotlib.pyplot as plt
import altair as alt
from vega_datasets import data

"""Inclusión de bases de datos,"""

students= pd.read_csv('student-mat.csv', 
                 sep = ';',
                 index_col=0,
                 error_bad_lines=False,)
students

"""¿Cuántos estudiantes viven en zona urbana o rural? ¿Cuántos de los estudiantes rurales 
son mujeres y cuántas son hombres? 
"""

# Urbana
Estudiantes_urbana = students[students['address']=="U"]
# Rural
Estudiantes_rural = students[students['address']=="R"]
print(str(len(Estudiantes_urbana))+" Estudiantes viven en una zona urbana,"+str(len(Estudiantes_rural))+" Estudiantes viven en una zona rural")

Hombres =Estudiantes_rural[Estudiantes_rural['sex']=="M"]
Mujeres = Estudiantes_rural[Estudiantes_rural['sex']=="F"]

print("Hay",str(len(Hombres))+" Hombres que son de zona rural,"+"Hay", str(len(Mujeres))+" Mujeres que son de una zona rural")

"""¿Cuántos estudiantes que viven en la zona rural se demoran en transportarse para llegar 
de la casa al colegio más de una hora? ¿Cuántos de ellos son mujeres y cuántos son 
hombres?
"""

unahoramas =Estudiantes_rural[Estudiantes_rural['traveltime']==4]
Hombres_R =unahoramas[unahoramas['sex']=="M"]
Mujeres_R = unahoramas[unahoramas['sex']=="F"]

print("Hay",str(len(unahoramas))+" estudiantes que son de zona rural y se demoran más de una hora, además ",str(len(Hombres_R))," son hombres y ",str(len(Mujeres_R)), " son mujeres")

"""¿Cuántos estudiantes que viven en la zona rural tienen más de 5 fallas? ¿Cuántos de ellos 
son mujeres y cuántos son hombres?
"""

masde5absences =Estudiantes_rural[Estudiantes_rural['absences']>5]
Hombres_R_A =masde5absences[masde5absences['sex']=="M"]
Mujeres_R_A = masde5absences[masde5absences['sex']=="F"]

print("Hay",str(len(masde5absences))+" estudiantes que son de zona rural y tienen más de 5 ausencias, además ",str(len(Hombres_R_A))," son hombres y ",str(len(Mujeres_R_A)), " son mujeres")

"""¿Cuántos estudiantes tienen madres y padres con un grado de escolaridad por encima de 
la educación secundaria? 
"""

edPar_sec = students[(students['Medu']==4) & (students['Fedu']==4)]

print("Hay",str(len(edPar_sec))+" estudiantes que tienen madres y padres con un grado de escolaridad por encima de la educación secundaria")

"""Se quiere ver la media de las notas de matemáticas de los estudiantes del colegio Gabriel 
Pereira vs Mousinho da Silveira, teniendo en cuenta si los estudiantes tienen o no internet 
en sus casas. Realice una visualización de datos teniendo en cuenta estas 3 variables.
"""

students['colegio'] = students.index

# Teniendo en cuenta que la base de datos es de matemáticas, tenemos:
# Final grade


sns.catplot(data = students,
            kind = "bar",
            estimator = np.mean,
            x = "internet",
            y = "G3",
            col = "colegio",
            palette = 'magma',
            ci = None)

# Teniendo en cuenta que la base de datos es de matemáticas, tenemos:
# Promedio de notas G

data = students[["G1","G2","G3"]]
students [["promedio"]]=data.mean(axis=1)


sns.catplot(data = students,
            kind = "bar",
            estimator = np.mean,
            x = "internet",
            y = "promedio",
            col = "colegio",
            palette = 'magma',
            ci = None)

"""Cree una nueva variable en la tabla que corresponda a la calificación total para cada uno 
de los estudiantes y responda ¿Cuál es la media, mediana, mínima y máxima calificación 
total?
"""

# Teniendo en cuenta que la variable promedio que realizé es el promedio de las calificaciones,
# se entenderá que esta es la calificacióón final.

students[["promedio"]].describe()

students[["promedio"]].median()

"""Media: 10,67
Mediana: 10,66
Minima: 1,33
Máxima: 19,33

Teniendo en cuenta que el dataset contiene tanto variables numéricas como variables 
categóricas responda ¿Qué tipo de análisis realizaría: Regresión o clasificación? Si fuera 
regresión o clasificación: ¿Qué variable usaría para predecir o clasificar? ¿Cuáles variables 
tiene la hipótesis que podrían servir para pronosticar o clasificar?

Rta: 

Dado que: "Los algoritmos de clasificación se usan cuando el resultado deseado es una etiqueta discreta, en otras palabras, son útiles cuando la respuesta al problema cae dentro de un conjunto finito de resultados posibles (...) y los algoritmos de regresión es útil para predecir productos que son continuos, eso significa que la respuesta a su pregunta se presenta mediante una cantidad que puede determinarse de manera flexible en función de las entradas del modelo en lugar de limitarse a un conjunto de etiquetas.

Se podrían hacer los dos tipos de análisis, dependiendo de lo que se desee estudiar.

Para clasificar:

Si por ejemplo se quiere estudiar una variable discreta como si tiene internet o no con base en algunas covariables, utilizaríía el de clasificacióón

Para clasificar tal vez podrían servir en el caso de esta variable dicótoma:

+ sex : sexo
+ age: edad
+ address: Si vive en la ruralidad o no
+ famsize : el tamaño de la familia
+ Pstatus : Si vive con los papás
+ Fedu: La educación del papá
+ Medu: La educación de la mamá
+ studytime:Tiempo de estudio
+ schoolsup: Si tiene soporte educativo
+ famsup: Si la familia tiene soporte educativo
+ higher: Si quiere continuar con estudios superiores
+ freetime: El tiempo libre

Para predecir:

Mientras si lo que quiero predecir es la calificación final de los estudiantes, utilizaría un analisis de regresióón.

Para predecir tal podría servir


+ sex : sexo
+ age: edad
+ address: Si vive en la ruralidad o no
+ famsize : el tamaño de la familia
+ Pstatus : Si vive con los papás
+ Fedu: La educación del papá
+ Medu: La educación de la mamá
+ studytime:Tiempo de estudio
+ schoolsup: Si tiene soporte educativo
+ famsup: Si la familia tiene soporte educativo
+ higher: Si quiere continuar con estudios superiores
+ freetime: El tiempo libre
+ paid : Clases extras
+ G1,G2: Notas anteriores 
+ Dalc: Consumo de alcohol
"""